import type { NavPage } from "@/types/lifeos";

export const DEFAULT_RULES = [
  "1️⃣ الاستمرارية فوق الكمال — 60% لسنة > 100% لأسبوع",
  "2️⃣ النوم أولاً — نوم أقل من 7 ساعات = خسارة 30% من الأداء",
  "3️⃣ ادفع لنفسك أولاً — ادخر يوم الراتب قبل أي شيء",
  "4️⃣ Deep Work يومي — ساعة تركيز > 5 ساعات متشتتة",
  "5️⃣ قارن نفسك بالأمس فقط",
  "6️⃣ لا تكسر السلسلة — Never Miss Twice",
  "7️⃣ المراجعة الأسبوعية مقدسة",
];

/** Navigation aligned with LifeOS_1.html */
export const NAV_PAGES: NavPage[] = [
  {
    id: "dashboard",
    href: "/dashboard",
    icon: "🏠",
    title: "لوحة التحكم",
    sub: "مركز التحكم الرئيسي",
    section: "الرئيسية",
  },
  {
    id: "goals",
    href: "/goals",
    icon: "🎯",
    title: "الأهداف",
    sub: "أحلامك بأهداف قابلة للقياس",
    section: "الرئيسية",
  },
  {
    id: "habits",
    href: "/habits",
    icon: "🔄",
    title: "العادات",
    sub: "مرتبطة بالأهداف والمشاريع",
    section: "الرئيسية",
  },
  {
    id: "areas",
    href: "/areas",
    icon: "🗂️",
    title: "المجالات",
    sub: "PARA — مناطق الحياة",
    section: "الرئيسية",
  },
  {
    id: "tasks",
    href: "/tasks",
    icon: "✅",
    title: "المهام",
    sub: "3 مهام كبيرة في اليوم",
    section: "الرئيسية",
  },
  {
    id: "planner",
    href: "/planner",
    icon: "📅",
    title: "Time Planner",
    sub: "جدولة ذكية — Day · Week · Month",
    section: "الرئيسية",
  },
  {
    id: "time",
    href: "/time",
    icon: "⏱️",
    title: "Time Intelligence",
    sub: "أين يذهب وقتك؟ Focus · Capacity",
    section: "الرئيسية",
  },
  {
    id: "body",
    href: "/body",
    icon: "💪",
    title: "الوزن والقياسات",
    sub: "تتبع التحول الجسدي",
    section: "الجسد والتغذية",
  },
  {
    id: "workouts",
    href: "/workouts",
    icon: "🏋️",
    title: "التمارين",
    sub: "نظام PPLUL",
    section: "الجسد والتغذية",
  },
  {
    id: "nutrition",
    href: "/nutrition",
    icon: "🍽️",
    title: "التغذية",
    sub: "3000 سعرة — ماكروز",
    section: "الجسد والتغذية",
  },
  {
    id: "books",
    href: "/books",
    icon: "📚",
    title: "المكتبة",
    sub: "12 كتاب/سنة",
    section: "المعرفة والمال",
  },
  {
    id: "finance",
    href: "/finance",
    icon: "💰",
    title: "المال والميزانية",
    sub: "دخل · مصروف · ادخار",
    section: "المعرفة والمال",
  },
  {
    id: "career",
    href: "/career",
    icon: "📈",
    title: "Career Hub",
    sub: "Roadmap · Skills · Interviews",
    section: "المعرفة والمال",
  },
  {
    id: "learning",
    href: "/learning",
    icon: "🧠",
    title: "Learning Hub",
    sub: "Paths · Courses · Sessions",
    section: "المعرفة والمال",
  },
  {
    id: "executive",
    href: "/executive",
    icon: "🏛️",
    title: "Executive",
    sub: "Life Score · Executive Summary",
    section: "التحليل والمراجعة",
  },
  {
    id: "ai",
    href: "/ai",
    icon: "🤖",
    title: "AI Coach",
    sub: "Insights · Brief · Coach",
    section: "التحليل والمراجعة",
  },
  {
    id: "reviews",
    href: "/reviews",
    icon: "📔",
    title: "المراجعات",
    sub: "يومية · أسبوعية · شهرية",
    section: "التحليل والمراجعة",
  },
  {
    id: "analytics",
    href: "/analytics",
    icon: "📊",
    title: "التحليلات",
    sub: "رؤى ذكية وأنماط",
    section: "التحليل والمراجعة",
  },
  {
    id: "archive",
    href: "/archive",
    icon: "🗄️",
    title: "الأرشيف",
    sub: "حفظ ومقارنة السنوات",
    section: "التحليل والمراجعة",
  },
  {
    id: "settings",
    href: "/settings",
    icon: "⚙️",
    title: "الإعدادات",
    sub: "الملف الشخصي والنسخ الاحتياطي",
    section: "الإعدادات",
  },
];

export function getPageMeta(pathname: string) {
  const page = NAV_PAGES.find((p) => pathname.startsWith(p.href));
  return page ?? NAV_PAGES[0];
}
